Repository cloudoperators/juno, pull requests merged in 2024-09, with the labels that each got.

#288 chore(infra): ignore husky
  .github/workflows/release.yaml
Labels: bug

#293 chore(infra): fix release update changeset force push CI workflow
  .changeset/dry-fans-ring.md
  .changeset/selfish-pots-count.md
  .github/workflows/ci-checks.yaml
  .github/workflows/ci-npm-packages.yaml
Labels: bug

#315 chore(ci): skip ci checks
  .changeset/quiet-points-appear.md
  .github/workflows/release.yaml
  package-lock.json
Labels: bug

#365 chore(infra): clean up task update
  apps/doop/package.json
  apps/example/package.json
  apps/greenhouse/apps/cluster-admin/package.json
  apps/greenhouse/apps/org-admin/package.json
  apps/greenhouse/apps/plugin-admin/package.json
  apps/greenhouse/apps/secret-admin/package.json
  apps/greenhouse/apps/team-admin/package.json
  apps/greenhouse/package.json
  apps/heureka/package.json
  apps/supernova/package.json
  package-lock.json
  packages/k8s-client/test/watch.test.ts
  packages/ui-components/package.json
  packages/ui-components/src/components/Checkbox/Checkbox.test.tsx
  packages/ui-components/src/components/CheckboxRow/CheckboxRow.test.tsx
  packages/ui-components/src/components/DataGrid/DataGrid.component.js
  packages/ui-components/src/components/Radio/Radio.test.tsx
  packages/ui-components/src/components/RadioRow/RadioRow.test.tsx
  packages/ui-components/src/components/Switch/Switch.test.js
  packages/ui-components/src/components/SwitchRow/SwitchRow.test.js
  packages/ui-components/src/deprecated_js/Checkbox/Checkbox.test.js
Labels: bug

#284 feat(ui): add FormattedText component
  .changeset/fast-pandas-behave.md
  commitlint.config.js
  packages/ui-components/rollup.config.js
  packages/ui-components/src/components/FormattedText/FormattedText.component.tsx
  packages/ui-components/src/components/FormattedText/FormattedText.stories.tsx
  packages/ui-components/src/components/FormattedText/FormattedText.test.tsx
  packages/ui-components/src/components/FormattedText/formatted-text.scss
  packages/ui-components/src/components/FormattedText/index.ts
  packages/ui-components/src/index.js
Labels: enhancement

#363 feat(ui): pageheader custom logo
  .changeset/changeset-pageheader-custom-logo.md
  .github/workflows/ci-checks.yaml
  apps/greenhouse/apps/cluster-admin/package.json
  apps/greenhouse/src/hooks/useAuthentication.js
  package-lock.json
  packages/ui-components/.storybook/tsconfig.storybook.json
  packages/ui-components/src/components/PageHeader/PageHeader.component.tsx
  packages/ui-components/src/components/PageHeader/PageHeader.stories.tsx
  packages/ui-components/src/components/PageHeader/PageHeader.test.tsx
  packages/ui-components/src/components/PageHeader/custom-logo-placeholders/custom-logo-landscape.png
  packages/ui-components/src/components/PageHeader/custom-logo-placeholders/custom-logo-landscape.svg
  packages/ui-components/src/components/PageHeader/custom-logo-placeholders/custom-logo-portrait.png
  packages/ui-components/src/components/PageHeader/custom-logo-placeholders/custom-logo-portrait.svg
  packages/ui-components/src/components/PageHeader/custom-logo-placeholders/custom-logo-square.png
  packages/ui-components/src/components/PageHeader/custom-logo-placeholders/custom-logo-square.svg
  packages/ui-components/src/img/JunoUI_logo.svg
  packages/ui-components/types/global.d.ts
Labels: enhancement

#394 feat(template): generator template for packages
  .changeset/gentle-cows-wave.md
  docs/getting-started.md
  package-lock.json
  package.json
  packages/template/README.md
  packages/template/__tests__/index.js
  packages/template/eslint.config.mjs
  packages/template/package.json
  packages/template/rollup.config.js
  packages/template/src/index.js
  packages/template/src/index.test.ts
  packages/template/src/index.ts
  packages/template/tsconfig.json
  packages/template/turbo.json
  packages/template/vite.config.ts
  packages/template/vitest.config.ts
  packages/template/vitest.setup.ts
Labels: enhancement

#397 chore(ui): change Toast to typescript
  .github/workflows/release.yaml
  packages/ui-components/src/components/Toast/Toast.component.tsx
  packages/ui-components/src/components/Toast/Toast.stories.tsx
  packages/ui-components/src/components/Toast/Toast.test.tsx
  packages/ui-components/src/components/Toast/index.ts
Labels: enhancement

#393 chore(greenhouse): add description to docker image
  .github/workflows/build-push-greenhouse-image.yaml
Labels: enhancement

#419 chore(ui): stabilize ui components tests everywhere
  packages/ui-components/src/components/SideNavigation/SideNavigation.test.tsx
  packages/ui-components/src/components/SideNavigationItem/SideNavigationItem.test.tsx
  packages/ui-components/src/components/TabNavigation/TabNavigation.test.tsx
  packages/ui-components/src/components/TabNavigationItem/TabNavigationItem.test.tsx
  packages/ui-components/src/components/Toast/Toast.test.tsx
  packages/ui-components/src/components/Tooltip/Tooltip.test.tsx
  packages/ui-components/src/components/TopNavigation/TopNavigation.test.tsx
Labels: bug

#467 chore(ui): migrate Stack component to TypeScript
  .changeset/modern-trees-mate.md
  packages/ui-components/src/components/Breadcrumb/Breadcrumb.component.js
  packages/ui-components/src/components/ButtonRow/ButtonRow.component.js
  packages/ui-components/src/components/InputGroup/InputGroup.component.js
  packages/ui-components/src/components/ModalFooter/ModalFooter.stories.js
  packages/ui-components/src/components/Pagination/Pagination.component.js
  packages/ui-components/src/components/SearchInput/SearchInput.component.js
  packages/ui-components/src/components/SecretText/SecretText.component.js
  packages/ui-components/src/components/Stack/Stack.component.tsx
  packages/ui-components/src/components/Stack/Stack.stories.tsx
  packages/ui-components/src/components/Stack/Stack.test.tsx
  packages/ui-components/src/components/Stack/index.ts
  packages/ui-components/src/deprecated_js/Stack/Stack.component.js
  packages/ui-components/src/deprecated_js/Stack/Stack.test.js
  packages/ui-components/src/deprecated_js/Stack/index.js
Labels: ui-components

#463 fix(ci): adds Conditional Check for Image Existence
  .github/workflows/build-push-greenhouse-image.yaml
  apps/greenhouse/docker/Dockerfile
  apps/greenhouse/docker/index.html
Labels: infrastructure

#458 chore(docs): adds a initial proposal for gh deployment
  docs/proposals/002_greenhouse_deployment.md
Labels: documentation

#462 chore(url-state-provider): switch to vite/vitest
  package-lock.json
  packages/url-state-provider/babel.config.js
  packages/url-state-provider/jest.config.js
  packages/url-state-provider/package.json
  packages/url-state-provider/rollup.config.js
  packages/url-state-provider/src/index.test.js
  packages/url-state-provider/vite.config.ts
  packages/url-state-provider/vitest.config.ts
  packages/url-state-provider/vitest.setup.ts
Labels: package

#469 chore(example): add needed packages to turbo deps
  apps/example/turbo.json
Labels: package

#466 feat(heureka): improves UX in different viewes
  .changeset/shy-waves-mix.md
  apps/heureka/src/App.jsx
  apps/heureka/src/App.test.jsx
  apps/heureka/src/components/CustomAppShell.jsx
  apps/heureka/src/components/filters/FilterSelect.jsx
  apps/heureka/src/components/issueMatches/IssueMatchesDetails.jsx
  apps/heureka/src/components/issueMatches/IssueMatchesList.jsx
  apps/heureka/src/components/issueMatches/IssueMatchesListItem.jsx
  apps/heureka/src/components/navEntries/NavEntry.jsx
  apps/heureka/src/components/navEntries/NavEntryContext.jsx
  apps/heureka/src/components/services/ServicesDetails.jsx
  apps/heureka/src/components/shared/Helper.jsx
  apps/heureka/src/components/shared/ListController.jsx
  apps/heureka/src/components/shared/PanelManager.jsx
  apps/heureka/src/hooks/useAppStore.js
  apps/heureka/src/hooks/useUrlState.js
  apps/heureka/src/lib/slices/createFiltersSlice.js
  apps/heureka/src/lib/slices/createGlobalsSlice.js
Labels: heureka

#420 chore(ui): migrate TextInput to TypeScript
  .changeset/poor-monkeys-mix.md
  packages/ui-components/src/components/FilterInput/FilterInput.component.js
  packages/ui-components/src/components/Form/Form.stories.js
  packages/ui-components/src/components/FormRow/FormRow.stories.js
  packages/ui-components/src/components/FormSection/FormSection.stories.js
  packages/ui-components/src/components/InputGroup/InputGroup.stories.js
  packages/ui-components/src/components/InputGroup/InputGroup.test.js
  packages/ui-components/src/components/Modal/Modal.stories.js
  packages/ui-components/src/components/Modal/Modal.test.js
  packages/ui-components/src/components/Pagination/Pagination.component.js
  packages/ui-components/src/components/TextInput/TextInput.component.tsx
  packages/ui-components/src/components/TextInput/TextInput.stories.tsx
  packages/ui-components/src/components/TextInput/TextInput.test.tsx
  packages/ui-components/src/components/TextInput/index.ts
  packages/ui-components/src/components/TextInputRow/TextInputRow.component.js
  packages/ui-components/src/deprecated_js/TextInput/TextInput.component.js
  packages/ui-components/src/deprecated_js/TextInput/TextInput.test.js
  packages/ui-components/src/deprecated_js/TextInput/index.js
  packages/ui-components/src/deprecated_js/TextInput/textinput.scss
Labels: ui-components

#470 chore(heureka): improves some naming
  apps/heureka/src/components/CustomAppShell.jsx
  apps/heureka/src/components/issueMatches/IssueMatchesListItem.jsx
Labels: heureka

#455 chore(ui): migrate Tabs and related components to TypeScript
  .changeset/serious-trains-sin.md
  packages/ui-components/src/components/CodeBlock/CodeBlock.stories.js
  packages/ui-components/src/components/MainTabs/MainTabs.component.tsx
  packages/ui-components/src/components/MainTabs/MainTabs.stories.tsx
  packages/ui-components/src/components/MainTabs/MainTabs.test.tsx
  packages/ui-components/src/components/MainTabs/index.ts
  packages/ui-components/src/components/Tab/Tab.component.tsx
  packages/ui-components/src/components/Tab/Tab.stories.tsx
  packages/ui-components/src/components/Tab/Tab.test.tsx
  packages/ui-components/src/components/Tab/index.ts
  packages/ui-components/src/components/TabList/TabList.component.tsx
  packages/ui-components/src/components/TabList/TabList.stories.tsx
  packages/ui-components/src/components/TabList/TabList.test.tsx
  packages/ui-components/src/components/TabList/index.ts
  packages/ui-components/src/components/TabNavigationItem/TabNavigationItem.test.tsx
  packages/ui-components/src/components/TabPanel/TabPanel.component.tsx
  packages/ui-components/src/components/TabPanel/TabPanel.stories.tsx
  packages/ui-components/src/components/TabPanel/TabPanel.test.tsx
  packages/ui-components/src/components/TabPanel/index.ts
  packages/ui-components/src/components/Tabs/Tabs.component.tsx
  packages/ui-components/src/components/Tabs/Tabs.stories.tsx
  packages/ui-components/src/components/Tabs/Tabs.test.tsx
  packages/ui-components/src/components/Tabs/index.ts
  packages/ui-components/src/deprecated_js/Tab/Tab.component.js
  packages/ui-components/src/deprecated_js/Tab/Tab.test.js
  packages/ui-components/src/deprecated_js/Tab/index.js
  packages/ui-components/src/deprecated_js/TabList/TabList.component.js
  packages/ui-components/src/deprecated_js/TabList/TabList.test.js
  packages/ui-components/src/deprecated_js/TabList/index.js
  packages/ui-components/src/deprecated_js/TabPanel/TabPanel.component.js
  packages/ui-components/src/deprecated_js/TabPanel/TabPanel.test.js
  packages/ui-components/src/deprecated_js/TabPanel/index.js
  packages/ui-components/src/deprecated_js/Tabs/Tabs.component.js
  packages/ui-components/src/deprecated_js/Tabs/Tabs.test.js
  packages/ui-components/src/deprecated_js/Tabs/index.js
Labels: ui-components

#464 chore(doop): migrate to vite/vitest
  .github/workflows/deploy-pr-preview.yaml
  apps/doop/.gitignore
  apps/doop/README.md
  apps/doop/__mocks__/client.js
  apps/doop/__mocks__/fileMock.js
  apps/doop/__mocks__/styleMock.js
  apps/doop/appProps.template.json
  apps/doop/babel.config.js
  apps/doop/esbuild.config.js
  apps/doop/helpers/appProps.js
  apps/doop/index.html
  apps/doop/jest.config.js
  apps/doop/package.json
  apps/doop/public/index.html
  apps/doop/secretProps.template.json
  apps/doop/setupTests.js
  apps/doop/src/App.jsx
  apps/doop/src/App.test.js
  apps/doop/src/App.test.jsx
  apps/doop/src/assets/juno-danger.svg
  apps/doop/src/assets/map.svg
  apps/doop/src/assets/rocket.gif
  apps/doop/src/db.json
  apps/doop/src/hooks/useCommunication.js
  apps/doop/src/hooks/useUrlState.js
  apps/doop/src/img/favicon-16x16.png
  apps/doop/src/img/favicon-32x32.png
  apps/doop/src/img/favicon.ico
  apps/doop/src/lib/store/createAuthDataSlice.jsx
  apps/doop/src/lib/store/createDataSlice.jsx
  apps/doop/src/lib/store/createDataSlice.test.jsx
  apps/doop/src/lib/store/createFiltersSlice.jsx
  apps/doop/src/lib/store/createFiltersSlice.test.jsx
  apps/doop/src/lib/store/createGlobalsSlice.jsx
  apps/doop/src/lib/store/createUserActivitySlice.jsx
  apps/doop/src/styles.module.scss
  apps/doop/turbo.json
  apps/doop/vite.config.ts
  apps/doop/vitest.config.ts
  apps/doop/vitest.setup.ts
  package-lock.json
Labels: Migration, doop

#485 fix(build): use ?inline for inline styles
  apps/doop/src/App.jsx
  apps/doop/src/styles.scss
  apps/example/src/App.jsx
  apps/example/src/styles.scss
  package-lock.json
Labels: bug, doop, app
