Repository cloudoperators/juno, pull requests merged in 2024-08, with the labels that each got.

#205 feat(k8s): MIgrate k8s-client under @cloudoperators/juno-k8s-client and TypeScript
  package-lock.json
  packages/eslint-config/juno-typescript.mjs
  packages/k8s-client/.gitignore
  packages/k8s-client/LICENSE
  packages/k8s-client/README.md
  packages/k8s-client/docker/Dockerfile.dev
  packages/k8s-client/eslint.config.mjs
  packages/k8s-client/package.json
  packages/k8s-client/src/apiErrorHandler.ts
  packages/k8s-client/src/client.ts
  packages/k8s-client/src/index.ts
  packages/k8s-client/src/logger.ts
  packages/k8s-client/src/request.ts
  packages/k8s-client/src/urlHelpers.ts
  packages/k8s-client/src/utils.ts
  packages/k8s-client/src/watch.ts
  packages/k8s-client/test/client.test.ts
  packages/k8s-client/test/index.test.ts
  packages/k8s-client/test/request.test.ts
  packages/k8s-client/test/urlHelpers.test.ts
  packages/k8s-client/test/utils.test.ts
  packages/k8s-client/test/watch.test.ts
  packages/k8s-client/tsconfig.json
  packages/k8s-client/vite.config.mts
  packages/k8s-client/vitest.config.ts
  packages/k8s-client/vitest.setup.ts
Labels: enhancement

#211 chore(ci): create a title check workflow
  .github/workflows/ci-checks.yaml
  .github/workflows/ci-title-lint-check.yaml
  .github/workflows/release.yaml
  packages/communicator/package.json
  packages/oauth/package.json
Labels: enhancement

#216 chore(k8s): delete axios dependency and update workflow
  .github/workflows/ci-title-lint-check.yaml
  .github/workflows/release.yaml
  package-lock.json
  packages/communicator/package.json
  packages/k8s-client/package.json
  packages/k8s-client/src/apiErrorHandler.ts
Labels: bug

#264 fix(communicator): vite and communicator version bump
  .changeset/appshell-render-topnavigation-embedded.md
  .changeset/small-poets-wink.md
  .changeset/wrapperClassName.md
  package-lock.json
  packages/communicator/CHANGELOG.md
  packages/communicator/package.json
  packages/communicator/tsconfig.json
  packages/communicator/tsup.config.ts
  packages/communicator/turbo.json
  packages/communicator/vite.config.mts
  packages/ui-components/CHANGELOG.md
  packages/ui-components/package.json
Labels: bug

#266 fix(communicator): change build output of communicator
  .changeset/sweet-cameras-develop.md
  packages/communicator/package.json
  packages/communicator/vite.config.mts
Labels: bug

#268 fix(docs): add release guidelines
  .changeset/real-masks-drum.md
  .github/workflows/pipeline-npm-package.yaml
  CONTRIBUTING.md
  docs/decision_monorepo_tooling.md
  docs/releases_guidelines.md
Labels: documentation

#270 chore(infra): integrate husky to the development process
  .github/workflows/ci-checks.yaml
  .github/workflows/pipeline-npm-package.yaml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  CONTRIBUTING.md
  commitlint.config.js
  docs/husky_commitlint_guide.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#271 chore(oauth): migrate OAuth package to Typescript
  .changeset/thin-sheep-rush.md
  package-lock.json
  packages/oauth/__tests__/__utils__/globalsMock.ts
  packages/oauth/__tests__/__utils__/idTokenMock.ts
  packages/oauth/__tests__/__utils__/oidcConfigMock.ts
  packages/oauth/__tests__/codeFlow.test.ts
  packages/oauth/__tests__/implicitFlow.test.ts
  packages/oauth/__tests__/mockedSession.test.ts
  packages/oauth/__tests__/oidcConfig.test.ts
  packages/oauth/__tests__/oidcSession.test.ts
  packages/oauth/__tests__/tokenHelpers.test.ts
  packages/oauth/eslint.config.mjs
  packages/oauth/package.json
  packages/oauth/src/codeFlow.ts
  packages/oauth/src/implicitFlow.ts
  packages/oauth/src/index.ts
  packages/oauth/src/mockedSession.ts
  packages/oauth/src/oidcConfig.ts
  packages/oauth/src/oidcSession.ts
  packages/oauth/src/oidcState.ts
  packages/oauth/src/tokenHelpers.ts
  packages/oauth/src/utils.ts
  packages/oauth/tsconfig.json
  packages/oauth/vite.config.mts
  packages/oauth/vitest.config.ts
  packages/oauth/vitest.setup.ts
Labels: enhancement

#278 chore(infra): unify config package
  .changeset/gentle-fans-explode.md
  .changeset/green-years-cry.md
  .changeset/tall-spoons-compete.md
  .github/workflows/ci-checks.yaml
  CONTRIBUTING.md
  apps/example/eslint.config.mjs
  apps/example/package.json
  apps/template/eslint.config.mjs
  apps/template/package.json
  docs/getting-started.md
  docs/releases_guidelines.md
  package-lock.json
  packages/communicator/eslint.config.mjs
  packages/communicator/package.json
  packages/communicator/tsconfig.json
  packages/config/README.md
  packages/config/eslint/juno-typescript.mjs
  packages/config/eslint/juno.mjs
  packages/config/package.json
  packages/config/typescript/base.json
  packages/config/typescript/react-app.json
  packages/eslint-config/CHANGELOG.md
  packages/eslint-config/README.md
  packages/k8s-client/eslint.config.mjs
  packages/k8s-client/package.json
  packages/k8s-client/tsconfig.json
  packages/k8s-client/vite.config.mts
  packages/messages-provider/eslint.config.mjs
  packages/messages-provider/package.json
  packages/oauth/__tests__/oidcConfig.test.ts
  packages/oauth/eslint.config.mjs
  packages/oauth/package.json
  packages/oauth/rollup.config.js
  packages/oauth/src/OAuthError.ts
  packages/oauth/src/oidcSession.ts
  packages/oauth/tsconfig.json
  packages/template/eslint.config.mjs
  packages/template/package.json
  packages/typescript-config/README.md
  packages/typescript-config/package.json
  packages/ui-components/eslint.config.mjs
  packages/ui-components/package.json
  packages/ui-components/tsconfig.build.json
  packages/ui-components/tsconfig.json
  packages/url-state-provider/eslint.config.mjs
  packages/url-state-provider/package.json
  packages/url-state-router/eslint.config.mjs
  packages/url-state-router/package.json
  packages/utils/eslint.config.mjs
  packages/utils/package.json
Labels: bug

#282 fix(config): rename mts config for release fix
  .changeset/old-bees-grow.md
  packages/communicator/vite.config.ts
  packages/k8s-client/eslint.config.mjs
  packages/k8s-client/vite.config.ts
  packages/k8s-client/vitest.config.ts
  packages/oauth/eslint.config.mjs
  packages/oauth/vite.config.ts
  packages/oauth/vitest.config.ts
Labels: bug

#285 chore(core): fix security deps problems
  .changeset/quick-badgers-behave.md
  package-lock.json
  packages/ui-components/package.json
Labels: enhancement

#286 chore(infra): fix release triggers
  .changeset/soft-garlics-do.md
  .github/workflows/ci-checks.yaml
  .gitignore
  .prettierignore
  package.json
Labels: bug
