Repository cloudoperators/juno, pull requests merged in 2025-05, with the labels that each got.

#900 chore(deps): update @floating-ui/react to the latest version (0.27.8)
  .changeset/angry-pillows-watch.md
  package-lock.json
  packages/ui-components/package.json
  packages/ui-components/src/components/Tooltip/Tooltip.test.tsx
  packages/ui-components/src/components/TooltipContent/TooltipContent.component.tsx
Labels: Technical Debt, ui-components, app, dependencies

#925 chore(deps): update storybook dependencies to the latest version
  .changeset/five-ravens-move.md
  package-lock.json
  packages/ui-components/.storybook/main.js
  packages/ui-components/package.json
  packages/ui-components/src/components/Button/Button.stories.tsx
  packages/ui-components/src/components/ComboBox/ComboBox.stories.tsx
  packages/ui-components/src/components/Icon/Icon.stories.ts
  packages/ui-components/src/components/NativeSelect/NativeSelect.stories.tsx
  packages/ui-components/src/components/Select/Select.stories.tsx
  packages/ui-components/src/components/TextInput/TextInput.stories.tsx
  packages/ui-components/src/components/Textarea/Textarea.stories.tsx
Labels: Technical Debt, ui-components, app

#949 chore(core): fix release ci
  .github/workflows/ci-checks.yaml
  .github/workflows/deploy-github-pages.yaml
  .github/workflows/release.yaml
  apps/greenhouse/src/components/core-apps/org-admin/components/plugins/plugins/components/Toolbar.tsx
  package.json
  packages/config/package.json
  packages/oauth/package.json
  packages/oauth/src/codeFlow.ts
  packages/ui-components/src/components/ComboBox/ComboBox.component.tsx
  packages/ui-components/src/components/FormRow/FormRow.test.tsx
  packages/ui-components/src/components/Navigation/Navigation.component.tsx
  packages/ui-components/src/hooks/useLocalStorage.ts
  pnpm-lock.yaml
Labels: infrastructure

#950 chore(ci): rework ci-checks workflow and use SHAs and fix duplication issues by using matrix
  .github/workflows/ci-checks.yaml
Labels: infrastructure

#924 fix(ui): add missing popupmenu exports
  .changeset/metal-roses-impress.md
  packages/ui-components/src/index.ts
Labels: ui-components

#952 chore(ci): rework title-check workflow, de-duplicate config, improve security and safely handle forks
  .github/workflows/ci-title-lint-check.yaml
  commitlint.config.js
  commitlint.config.mjs
Labels: infrastructure

#953 chore(ci): rework github pages workflows to use SHAs and skip previews on forks
  .github/workflows/deploy-github-pages.yaml
  .github/workflows/deploy-pr-preview.yaml
Labels: infrastructure

#960 chore(ci): add pull-requests: write permission to PR preview workflow
  .github/workflows/deploy-pr-preview.yaml
  apps/carbon/README.md
Labels: infrastructure

#963 chore(ci): fixes renovate configuration
  .github/renovate.json
Labels: infrastructure

#942 chore(core): upgrade React 19 monorepo
  .changeset/deep-toes-make.md
  .changeset/vast-melons-call.md
  apps/carbon/package.json
  apps/carbon/src/components/ErrorBoundary/ErrorBoundary.test.tsx
  apps/doop/package.json
  apps/doop/src/components/shared/Collapsible.tsx
  apps/example/package.json
  apps/greenhouse/package.json
  apps/greenhouse/src/components/Extensions.tsx
  apps/greenhouse/src/components/core-apps/org-admin/components/plugins/plugindefinitions/components/PluginDefinitionDetail.tsx
  apps/heureka/package.json
  apps/heureka/src/components/Services/useFetchServiceImageVersionIssues.ts
  apps/heureka/src/components/Services/useFetchServiceImageVersions.ts
  apps/heureka/src/components/Services/useFetchServices.ts
  apps/heureka/src/components/common/ErrorBoundary/index.test.tsx
  apps/supernova/package.json
  apps/template/package.json
  apps/template/src/components/AppContent.tsx
  apps/template/src/components/WelcomeView.tsx
  docs/create-your-own-app.md
  package.json
  packages/config/eslint/juno-typescript.mjs
  packages/config/eslint/juno.mjs
  packages/k8s-client/package.json
  packages/messages-provider/package.json
  packages/ui-components/package.json
  packages/ui-components/src/components/Checkbox/Checkbox.component.tsx
  packages/ui-components/src/components/ComboBox/ComboBox.component.tsx
  packages/ui-components/src/components/DataGridCell/DataGridCell.stories.tsx
  packages/ui-components/src/components/DataGridCheckboxCell/DataGridCheckboxCell.stories.tsx
  packages/ui-components/src/components/DataGridHeadCell/DataGridHeadCell.stories.tsx
  packages/ui-components/src/components/DataGridRow/DataGridRow.stories.tsx
  packages/ui-components/src/components/DateTimePicker/DateTimePicker.component.tsx
  packages/ui-components/src/components/Form/Form.stories.tsx
  packages/ui-components/src/components/InputGroup/InputGroup.stories.tsx
  packages/ui-components/src/components/Message/Message.test.tsx
  packages/ui-components/src/components/Modal/Modal.component.tsx
  packages/ui-components/src/components/NativeSelectOptionGroup/NativeSelectOptionGroup.test.tsx
  packages/ui-components/src/components/Pagination/Pagination.stories.tsx
  packages/ui-components/src/components/Radio/Radio.component.tsx
  packages/ui-components/src/components/Select/Select.component.tsx
  packages/ui-components/src/components/Select/Select.stories.tsx
  packages/ui-components/src/hooks/useEndlessScrollList.test.tsx
  packages/ui-components/src/hooks/useEndlessScrollList.tsx
  pnpm-lock.yaml
Labels: enhancement, Technical Debt, app, dependencies
